[package]
name = "paper-engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
wgpu = "23.0"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["png"] }
log = "0.4"
android_logger = "0.14"
lazy_static = "1.4"
tokio = { version = "1.35", features = ["rt"] }


[target.'cfg(target_os = "android")'.dependencies]
ndk = "0.9"
ndk-sys = "0.6"
ndk-context = "0.1"
raw-window-handle = "0.6"

[profile.release]
opt-level = 3
lto = true
strip = true
